title: Barty's Guide to Caelum's Landing
author:
  name: GitHub Repository
  email: https://github.com/archbardinexile/BGCL
description: A custom setting for D&D 5e
theme: minima
minima:
  skin: auto
header-pages:
  - page.md
