title: Barty's Guide to Caelum's Landing
author:
  name: By Alexander Birch
description: A custom setting for D&D 5e
#theme: minima
remote_theme: jekyll/minima
minima:
  skin: auto
header_pages:
  - getting-started.md
