# About

title: Barty's Guide
author:
  name: Alexander Birch
description: Barty's Guide to Caelum's Landing is a custom setting for Dungeons and Dragons Fifth Edition.
permalink: :title

# Theme

remote_theme: jekyll/minima
minima:
  skin: auto

# Content

  nav_pages:
    - getting-started.md
    - locations.md
    - characters.md
    - timeline.md
    - players.md
    - items.md
    - spells.md
