# About

title: Barty's Guide
author:
  name: Alexander Birch
description: Barty's Guide to Caelum's Landing is an open source custom setting for Dungeons and Dragons Fifth Edition.

# Theme

remote_theme: jekyll/minima
minima:
  skin: auto

# Content

header_pages:
  - getting-started.md
  - timeline.md
