# About

title: Barty's Guide to Caelum's Landing
author:
  name: Alexander Birch
description: A custom setting for Dungeons and Dragons Fifth Edition. View the [GitHub Repository](https://github.com/archbardinexile/BGCL).

# Theme

remote_theme: jekyll/minima
minima:
  skin: auto

# Content

header_pages:
  - getting-started.md
  - timeline.md
