# About

title: Barty's Guide to Caelum's Landing
author:
  name: Alexander Birch
description: Barty's Guide to Caelum's Landing is an open source custom setting for Dungeons and Dragons Fifth Edition.

# Theme

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/archbardinexile/BGCL" }

# Content

header_pages:
  - getting-started.md
  - timeline.md
